import { randomBytes } from 'node:crypto';
import { pool } from '../db/pool.js';
import { decryptSecret, encryptSecret, generateApiKey, parseApiKey, secretMatches } from '../security/credentials.js';

export async function createTenant(name:string,slug:string){ return (await pool.query('insert into tenants(name,slug) values($1,$2) returning *',[name,slug])).rows[0]; }
export async function getTenant(id:string){ return (await pool.query('select id,name,slug,status,created_at,updated_at from tenants where id=$1',[id])).rows[0] ?? null; }
export async function issueApiKey(tenantId:string,name:string){ const key=generateApiKey(); const row=(await pool.query('insert into tenant_api_keys(tenant_id,key_prefix,secret_hash,name) values($1,$2,$3,$4) returning id,tenant_id,key_prefix,name,created_at',[tenantId,key.prefix,key.secretHash,name])).rows[0]; return {...row,key:key.plaintext}; }
export async function revokeApiKey(id:string){ return (await pool.query('update tenant_api_keys set revoked_at=now() where id=$1 and revoked_at is null returning id',[id])).rowCount===1; }
export async function authenticateApiKey(value:string){ const parsed=parseApiKey(value); if(!parsed)return null; const row=(await pool.query(`select k.id,k.tenant_id,k.secret_hash,t.status from tenant_api_keys k join tenants t on t.id=k.tenant_id where k.key_prefix=$1 and k.revoked_at is null`,[parsed.prefix])).rows[0]; if(!row||!secretMatches(parsed.secret,row.secret_hash)||row.status!=='active')return null; void pool.query('update tenant_api_keys set last_used_at=now() where id=$1',[row.id]); return row.tenant_id as string; }
export async function addBankAccount(tenantId:string,input:{account_number:string;bank_code?:string;label?:string}){ return (await pool.query('insert into bank_accounts(tenant_id,account_number,bank_code,label) values($1,$2,$3,$4) returning *',[tenantId,input.account_number,input.bank_code??null,input.label??null])).rows[0]; }
export async function upsertWebhook(tenantId:string,url:string,secret:string|undefined,encryptionKey:string){ if(!/^https:\/\//i.test(url))throw new Error('Webhook URL phải dùng HTTPS'); const plaintext=secret??randomBytes(32).toString('base64url'); const encrypted=encryptSecret(plaintext,encryptionKey); const row=(await pool.query(`insert into tenant_webhooks(tenant_id,url,secret_encrypted) values($1,$2,$3) on conflict(tenant_id) do update set url=excluded.url,secret_encrypted=excluded.secret_encrypted,active=true,updated_at=now() returning id,tenant_id,url,active,created_at,updated_at`,[tenantId,url,encrypted])).rows[0]; return {...row,secret:plaintext}; }
export async function findRoute(accountNumber:string){ return (await pool.query(`select b.id bank_account_id,b.tenant_id,w.id webhook_id,w.url,w.secret_encrypted from bank_accounts b join tenants t on t.id=b.tenant_id left join tenant_webhooks w on w.tenant_id=t.id and w.active where b.account_number=$1 and b.active and t.status='active'`,[accountNumber])).rows[0]??null; }
export function webhookSecret(encrypted:string,key:string){return decryptSecret(encrypted,key);}
