import { randomBytes } from 'node:crypto';
import { pool } from '../db/pool.js';
import { hashSecret } from '../security/credentials.js';

export async function inviteOwner(tenantId:string,emailInput:string){
 const email=emailInput.trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error('Email không hợp lệ');
 const token=randomBytes(32).toString('base64url'),hash=hashSecret(token);
 const client=await pool.connect();try{await client.query('begin');const user=(await client.query(`insert into tenant_users(email) values($1) on conflict(email) do update set email=excluded.email returning id,email`,[email])).rows[0];await client.query(`insert into tenant_memberships(user_id,tenant_id,role) values($1,$2,'owner') on conflict(user_id,tenant_id) do update set role='owner'`,[user.id,tenantId]);await client.query(`insert into tenant_login_tokens(user_id,tenant_id,token_hash,expires_at) values($1,$2,$3,now()+interval '30 minutes')`,[user.id,tenantId,hash]);await client.query('commit');return{email,token};}catch(e){await client.query('rollback');throw e;}finally{client.release();}
}
export async function consumeLoginToken(token:string){const hash=hashSecret(token),client=await pool.connect();try{await client.query('begin');const row=(await client.query(`select l.id,l.user_id,l.tenant_id,u.email,t.name tenant_name from tenant_login_tokens l join tenant_users u on u.id=l.user_id join tenants t on t.id=l.tenant_id where l.token_hash=$1 and l.consumed_at is null and l.expires_at>now() for update`,[hash])).rows[0];if(!row){await client.query('rollback');return null;}await client.query('update tenant_login_tokens set consumed_at=now() where id=$1',[row.id]);await client.query('commit');return row;}catch(e){await client.query('rollback');throw e;}finally{client.release();}}
export async function membership(userId:string,tenantId:string){return(await pool.query(`select m.role,u.email,t.name tenant_name,t.status from tenant_memberships m join tenant_users u on u.id=m.user_id join tenants t on t.id=m.tenant_id where m.user_id=$1 and m.tenant_id=$2`,[userId,tenantId])).rows[0]??null;}
export async function portalDashboard(tenantId:string){const [tenant,connection,accounts]=await Promise.all([pool.query('select id,name,slug,status from tenants where id=$1',[tenantId]),pool.query('select id,status,scopes,last_error,updated_at from sepay_connections where tenant_id=$1',[tenantId]),pool.query(`select id,account_number,bank_code,label,active,source,sepay_account_id,sepay_webhook_id,sync_status from bank_accounts where tenant_id=$1 order by created_at`,[tenantId])]);return{tenant:tenant.rows[0],connection:connection.rows[0]??null,accounts:accounts.rows};}
