import { randomBytes } from 'node:crypto';
import { loadConfig } from '../config.js';
import { pool } from '../db/pool.js';
import { decryptSecret,encryptSecret,hashSecret } from '../security/credentials.js';
export const SEPAY_SCOPES='bank-account:read webhook:read webhook:write webhook:delete';
export type SepayBankAccount={id:string|number;account_number:string;bank_code?:string;bank_short_name?:string;account_holder_name?:string;active?:boolean};
type TokenResponse={access_token:string;refresh_token:string;expires_in:number;scope?:string};
function configured(){const c=loadConfig();if(!c.sepayOauthClientId||!c.sepayOauthClientSecret||!c.sepayOauthRedirectUri||!c.webhookEncryptionKey)throw new Error('SePay OAuth chưa được cấu hình');return c;}
export async function beginOauth(tenantId:string,userId:string){const c=configured(),state=randomBytes(32).toString('base64url');await pool.query(`insert into sepay_oauth_states(tenant_id,user_id,state_hash,expires_at) values($1,$2,$3,now()+interval '10 minutes')`,[tenantId,userId,hashSecret(state)]);const q=new URLSearchParams({response_type:'code',client_id:c.sepayOauthClientId,redirect_uri:c.sepayOauthRedirectUri,scope:SEPAY_SCOPES,state});return`https://my.sepay.vn/oauth/authorize?${q}`;}
export async function consumeState(state:string){const client=await pool.connect();try{await client.query('begin');const row=(await client.query(`select id,tenant_id,user_id from sepay_oauth_states where state_hash=$1 and consumed_at is null and expires_at>now() for update`,[hashSecret(state)])).rows[0];if(!row){await client.query('rollback');return null;}await client.query('update sepay_oauth_states set consumed_at=now() where id=$1',[row.id]);await client.query('commit');return row;}catch(e){await client.query('rollback');throw e;}finally{client.release();}}
async function tokenRequest(body:URLSearchParams){const response=await fetch('https://my.sepay.vn/oauth/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','accept':'application/json'},body,redirect:'manual'});if(!response.ok)throw new Error(`SePay token endpoint trả HTTP ${response.status}`);return await response.json() as TokenResponse;}
export async function exchangeCode(tenantId:string,code:string){const c=configured(),tokens=await tokenRequest(new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:c.sepayOauthRedirectUri,client_id:c.sepayOauthClientId,client_secret:c.sepayOauthClientSecret}));await saveTokens(tenantId,tokens);}
async function saveTokens(tenantId:string,t:TokenResponse){const c=configured();await pool.query(`insert into sepay_connections(tenant_id,access_token_encrypted,refresh_token_encrypted,access_token_expires_at,refresh_token_expires_at,scopes,status,last_error) values($1,$2,$3,now()+make_interval(secs=>$4),now()+interval '1 month',$5,'active',null) on conflict(tenant_id) do update set access_token_encrypted=excluded.access_token_encrypted,refresh_token_encrypted=excluded.refresh_token_encrypted,access_token_expires_at=excluded.access_token_expires_at,refresh_token_expires_at=excluded.refresh_token_expires_at,scopes=excluded.scopes,status='active',last_error=null,updated_at=now()`,[tenantId,encryptSecret(t.access_token,c.webhookEncryptionKey),encryptSecret(t.refresh_token,c.webhookEncryptionKey),t.expires_in,t.scope??SEPAY_SCOPES]);}
async function accessToken(tenantId:string){const c=configured(),row=(await pool.query('select * from sepay_connections where tenant_id=$1 and status=$2',[tenantId,'active'])).rows[0];if(!row)throw new Error('Tenant chưa kết nối SePay');if(new Date(row.access_token_expires_at).getTime()>Date.now()+60000)return decryptSecret(row.access_token_encrypted,c.webhookEncryptionKey);const refresh=decryptSecret(row.refresh_token_encrypted,c.webhookEncryptionKey),tokens=await tokenRequest(new URLSearchParams({grant_type:'refresh_token',refresh_token:refresh,client_id:c.sepayOauthClientId,client_secret:c.sepayOauthClientSecret}));await saveTokens(tenantId,tokens);return tokens.access_token;}
async function api(tenantId:string,path:string,init:RequestInit={}){const token=await accessToken(tenantId),response=await fetch(`https://my.sepay.vn/api/v1${path}`,{...init,headers:{accept:'application/json',authorization:`Bearer ${token}`,...init.headers},redirect:'manual'});if(!response.ok)throw new Error(`SePay API trả HTTP ${response.status}`);return response.status===204?null:response.json();}
export async function syncAccounts(tenantId:string){const payload=await api(tenantId,'/bank-accounts') as any,items=(payload?.data??payload) as SepayBankAccount[];if(!Array.isArray(items))throw new Error('SePay trả danh sách tài khoản không hợp lệ');const connection=(await pool.query('select id from sepay_connections where tenant_id=$1',[tenantId])).rows[0];for(const a of items){const number=String(a.account_number),existing=(await pool.query('select id,tenant_id from bank_accounts where account_number=$1',[number])).rows[0];if(existing&&existing.tenant_id!==tenantId)throw new Error(`Tài khoản ${number} đang thuộc tenant khác`);if(existing){await pool.query(`update bank_accounts set bank_code=$2,label=$3,source='sepay_oauth',sepay_account_id=$4,sepay_connection_id=$5,verified_at=now(),sync_status=case when active then 'active' else 'synced' end,updated_at=now() where id=$1`,[existing.id,a.bank_code??null,a.bank_short_name??a.account_holder_name??null,String(a.id),connection.id]);}else{await pool.query(`insert into bank_accounts(tenant_id,account_number,bank_code,label,active,source,sepay_account_id,sepay_connection_id,verified_at,sync_status) values($1,$2,$3,$4,false,'sepay_oauth',$5,$6,now(),'synced')`,[tenantId,number,a.bank_code??null,a.bank_short_name??a.account_holder_name??null,String(a.id),connection.id]);}}return items.length;}
export async function activateAccount(tenantId:string,accountId:string,receiverToken:string,receiverUrl:string){const row=(await pool.query(`select * from bank_accounts where id=$1 and tenant_id=$2 and source='sepay_oauth'`,[accountId,tenantId])).rows[0];if(!row)throw new Error('Không tìm thấy tài khoản');if(row.sepay_webhook_id){await pool.query('update bank_accounts set active=true where id=$1',[row.id]);return;}
 const payload=await api(tenantId,'/webhooks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({bank_account_id:Number(row.sepay_account_id),name:'GGPay incoming transactions',event_type:'In_only',authen_type:'Api_Key',webhook_url:receiverUrl,is_verify_payment:0,skip_if_no_code:0,active:1,only_va:0,retry_conditions:{non_2xx_status_code:1},api_key:receiverToken,request_content_type:'Json'})}) as any;const id=payload?.id??payload?.data?.id;if(!id)throw new Error('SePay không trả webhook id');await pool.query(`update bank_accounts set active=true,sepay_webhook_id=$2,sync_status='active',updated_at=now() where id=$1`,[row.id,String(id)]);}
export async function deactivateAccount(tenantId:string,accountId:string){const row=(await pool.query('select * from bank_accounts where id=$1 and tenant_id=$2',[accountId,tenantId])).rows[0];if(!row)throw new Error('Không tìm thấy tài khoản');if(row.sepay_webhook_id)await api(tenantId,`/webhooks/${encodeURIComponent(row.sepay_webhook_id)}`,{method:'DELETE'});await pool.query(`update bank_accounts set active=false,sepay_webhook_id=null,sync_status='synced',updated_at=now() where id=$1`,[row.id]);}
